#!/bin/bash
#source /cvmfs/sft.cern.ch/lcg/views/setupViews.csh LCG_104 ${SCRAM_ARCH_LCG}
#
GEANT4VERSION=11.0.2
GEANT4LOCATION=/cvmfs/sft.cern.ch/lcg/views/LCG_96b/x86_64-centos7-gcc62-opt
#
echo "GEANT4LOCATION=${GEANT4LOCATION}" > config.txt
#
./configure --with-geant4=${GEANT4LOCATION}
